### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by manuligit** [manuligit/mapplaces#1]
# API / Backend
* [ ] #2 As an API, I want to have a CRUD (Create, Read, Update, Delete) structure for Places. 
* [ ] #3 As an API, I want to have a CRUD structure for Place keywords.
* [ ] #2 As a Place, I want to have the following data:
  - Title
  - Description
  - Map coordinates (Latitude and Longitude)
  - Opening hours
* [ ] #3 As a Place keyword, I want to have the following data:
  - Label
  - What Places I’m associated to

# Frontend
* [ ] #4  As a User, I want to be able to add new Places. 
* [ ] #5 As a User, I want to be able to remove existing Places.
* [ ] #6 As a User, I want to be able to edit the title, description, opening hours and coordinates of an existing Place.
* [ ] #7 As a User, I want to be able to search Places by title.
* [ ] #8 As a User, I want to be able to filter Places to display only open places.
* [ ] #9 As a Map, I want to be able to display the currently filtered set of Places.
* [ ] #10 As a User, I want to be able to add, edit and remove keywords for a Place.
* [ ] #11 As a User, I want to be able to filter Places based on a list of Place keywords.
* [ ] #12 As a User, I want to have a clear, and if possible, a good-looking user interface to do all these actions in.
* [ ] #13 As an Application, I want to be a single-page application so that users don’t have to reload the page when they filter or add Places, for example.

# Extra respect
* [ ] #14 As a User, I want to select a Place’s location (coordinates) straight from the Map when adding a Place or editing a Place
* [ ] #15 As a User, I want to be able to set an existing Place as a favorite Place.
* [ ] #16 As a User, I want to be able to remove a Place from the list of my favorite Places.
* [ ] #17 As a User, I want to filter Places to display only my favorites.

# Documentation
* [ ] #18 A readme file should be supplied when returning this exercise for review. The readme should contain system requirements, installation instructions and possible instructions about using sample data.
